version: '3.8'

services:
    pgvector:
      hostname: db
      image: ankane/pgvector
      ports:
        - 5432:5432
      restart: always
      environment:
        - POSTGRES_DB=vectordb
        - POSTGRES_USER=testuser
        - POSTGRES_PASSWORD=testpwd
        - POSTGRES_HOST_AUTH_METHOD=trust
      volumes:
        - /db:/var/lib/postgresql